### ISSUE TITLE
Handle included files

### ISSUE THREAD

**Issue by thelfensdrfer** [tmont/nginx-conf#11]
How does this library handle included "sub-configs"? The files property is already an array `files: [ '/etc/nginx/nginx.conf' ]` but only contains the one file parsed. And I can't access the values in the included files so I assume includes are not treated specially?

**Comment by tmont** [comment]
Yeah, included files are not parsed. Whatever file you originally parse is the one you interact with.

**Comment by thelfensdrfer** [comment]
Is this intended? If not, I could try my luck and create a pr if it is successful.

**Comment by tmont** [comment]
Yes, it was by design to not detect included files. By default, it just handles one file at a time. I think there would be some minor complications with managing "child" config files, and keeping track of which files got changed.

If you want to give it a try, go for it!

**Comment by thelfensdrfer** [comment]
Ok, i will close the issue for now, but will definitely come back later and give it a try.
