### ISSUE TITLE
Variables get Removed during Parsing

### ISSUE THREAD

**Issue by raynigon** [tmont/nginx-conf#18]
**Description:**
Example Config:
`/build${mobile_path}/`
If it gets parsed and serialized again, the configuration looks like
`/build$`
For More Information see: raynigon/vscode-nginx-formatter#2

**Expected Behaviour:**
The expected bahviour would be to have the same variables in the configuration as before the config was parsed.

**Testing:**
Sample Code (TS) for testing:
```
const promise = new Promise<string>((resolve, reject)=>{
  nginx.parse(document, (error, tree)=>{
    if(error!=null){
      reject("Unable to parse Document: "+error);
      return;
    }
    const text = (new nginx.NginxConfFile(tree)).toString();
    resolve(text);
  });
});
```

**Comment by tmont** [comment]
fixed in `nginx-conf@1.5.0`.

Thanks for the bug report.
