### ISSUE TITLE
Can I keep blank lines when formatting?

### ISSUE THREAD

**Issue by richex-cn** [tmont/nginx-conf#24]
```
server {
    listen 9090;
    server_name localhost;

    location / {
        root /path/to/www;
    }
    
    location /exact/match.html {
        allow all;
    }
}
```

The above is what I expected, But expansion will produce the following results:

```
server {
    listen 9090;
    server_name localhost;
    location / {
        root /path/to/www;
    }
    location /exact/match.html {
        allow all;
    }
}
```

**Comment by Ali-Azmoud** [comment]
Hi, just put a `\n` before the name of the key, but it removes indents which is worse in my opinion
```
conf.nginx.http.server[1]._add('\nlisten', '80');
```

**Comment by tmont** [comment]
Sorry, this is incredibly old but in my defense I'm incredibly lazy.

No, you cannot keep the original formatting. That is by design. Well, by design as my "laziness" was by design. 

Formatting is outside the scope of this library, it's only meant to give programmatic access to the configuration.
